[package]
name = "rmenu"
version = "0.1.0"
edition = "2024"
license = "MIT OR APACHE-2.0"

[dependencies]
flexi_logger = "0.30.1"
log = "0.4.27"
sdl2 = { version = "0.37.0", features = ["ttf", "gfx"] }
thiserror = "2.0.12"
toml_edit = "0.22.26"
